repos:
  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.1"
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --show-files, --exit-non-zero-on-fix, "--line-length=100"]

  # Black - autoformatter
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10  

  # MyPy - type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language_version: python3.10
        additional_dependencies:
          - types-requests